### PR TITLE
cli: make --version print rome version

### PR DESCRIPTION
**Pull request by thecodrr**
After this, we will no longer be printing `undefined` after `rome --version` but the actual version. Currently, this version is gotten directly from the root `package.json`.

### CODE REVIEW

**Comment by sebmck** [comment]
Nice! The version is actually already available from:

```
import {VERSION} from '@romejs/core';
```

We shouldn't need to prefix the version either since we should do that in the cli-flags module, and if not, then we should.

**Comment by thecodrr** [comment]
That's the core version isn't it? If we use that, what's the root level package.json version for? I initially used `@romejs/core` version but thought it was only the core package version...

**Comment by thecodrr** [comment]
@sebmck should I make the changes in this PR or...?

**Comment by thecodrr** [comment]
@sebmck Removed all versions from package.json and updated the `VERSION` to use the root package.json.

**Comment by sebmck** [comment]
Thank you so much!

**Pull request merged**
