### PR TITLE
No cond assign eslint implementation

### PR DESCRIPTION
**Pull request by macovedj**
Going through https://github.com/facebookexperimental/rome/issues/94. [eslint](https://eslint.org/docs/rules/no-cond-assign) has two options for this rule, one that allows exception via parens, and the other which would need ignoring to escape.  I implemented the latter, because I don't think people should be encouraged to use paren, but I could implement it with parens if solid reasoning were provided.

### CODE REVIEW

**Comment by macovedj** [comment]
> [eslint](https://eslint.org/docs/rules/no-cond-assign) has two options for this rule, one that allows exception via parens, and the other which would need ignoring to escape. I implemented the latter, because I don't think people should be encouraged to use paren, but I could implement it with parens if solid reasoning were provided.
>
Lol.  The project currently violates this lint rule if we don't allow parens right [here](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-generator/Buffer.ts#LC207).  It feels to me like there's a better way to do this, but also I now see why parens would be desired.  What do you think @sebmck?

**Comment by sebmck** [comment]
Heh, I believe that's code left over from `babel-generator`. You should be able to replace that with:

```
while (true) {
  const item = this._queue.pop();
  if (item === undefined) {
    break;
  } else {
    this._append(...item);
  }
}
```

Makes it a lot clearer what the code is doing.

Feel free to do that in this PR!

**Comment by sebmck** [comment]
The rest of the PR looks good to me!

**Comment by macovedj** [comment]
> Heh, I believe that's code left over from `babel-generator`. You should be able to replace that with:
> 
> ```
> while (true) {
>   const item = this._queue.pop();
>   if (item === undefined) {
>     break;
>   } else {
>     this._append(...item);
>   }
> }
> ```
> 
> Makes it a lot clearer what the code is doing.
> 
> Feel free to do that in this PR!

Done!

**Comment by sebmck** [comment]
Looks good, thank you!

**Pull request merged**
