### PR TITLE
Fix typo (past participle of run is run)

### PR DESCRIPTION
**Pull request by theodore-s-beers**

### CODE REVIEW

**Comment by sebmck** [comment]
> past participle of run is run

Says who? From [Wikitionary](https://en.wiktionary.org/wiki/ran#Verb):

> 2. simple past tense of run
> 3. (nonstandard, colloquial) past participle of run

**Comment by theodore-s-beers** [comment]
Where nonstandard usage is intentional, by all means let it remain.

A Quora thread on this point, with several useful answers:

https://www.quora.com/What-is-the-past-participle-of-the-word-run

**Comment by sebmck** [comment]
This is not a good use of my time or yours. Feel free to submit PRs that are more substantive than this one.

**Comment by theodore-s-beers** [comment]
I agree. Submitting the PR took literally seconds, all in-browser. What followed was a waste of my time.

P.S. There's another prose error in the docs, just after this one ("There is currently no options"). I didn't notice it until a few minutes later. Have a nice day.

**Pull request closed without merging**
