### PR TITLE
Add dirty checks to `lint` and `ci`

### PR DESCRIPTION
**Pull request by sebmck**
This PR adds an error when you try to run `rome ci`, `rome lint --fix`, and `rome lint --review` when you have uncommitted files. In order to bypass the check you can add the flag `--allow-dirty`. This is what the error looks like:

Screenshot from 2020-04-20 15-33-17

Explanation is provided in the diagnostic. We should encourage people to commit before running these commands as we might be performing potentially unsafe fixes, and without a significant amount of testing the code formatter or lint rules could produce broken code. Even if we are confident in the stability of the linter I think it's worth encouraging this so we can be heavy on lint fixes.

(Ignore the `--compiler-options-per-file` flag in the screenshot)

### CODE REVIEW

**Comment by sebmck** [comment]
I'm uncertain about this workflow. We can iterate on it later.

**Comment by kennetpostigo** [comment]
Not sure how useful this is but, we use husky and lint staged as commit hooks to run linting, formatting and type checking on commit. 

Yesterday a friend of mine and I were working on a feature and fixing outstanding issues on vscode live share. And as my friend was committing code the githooks were running. As they were running live share got into a weird state and bricked for both of us all our changes. Our terminals were halted and we thought our code was lost.

However these git hooks apparently stashed our code when this happened and saved hours of our work. Might be useful to add something like this to rome. @sebmck

**Comment by sebmck** [comment]
@kennetpostigo Oh that's cool. Do you know how it works? My only usage has been running `git stash` and `git stash pop` :stuck_out_tongue:

**Comment by kennetpostigo** [comment]
Luckily we took a screen-shot of this:
image

Hope it's helpful @sebmck

**Pull request merged**
