### PR TITLE
js-compiler: split lint tests into individual files

### PR DESCRIPTION
**Pull request by yangshun**
## Summary

Move individual tests from `packages/@romejs/js-compiler/__rtests__/lint.ts` to `packages/@romejs/js-compiler/transforms/lint/__rtests__/`.

I didn't move `packages/@romejs/js-compiler/__rtests__/lint.ts` as I believe there are open PRs that added their tests there. I can move either move that file in this PR or let those open PRs get merged into the file and split that file again and move it later on. Let me know which approach you prefer!

### CODE REVIEW

**Comment by yangshun** [comment]
@KevinKelbie 

Those are tests. The implementation is untouched. This is the current structure:

- implementation: `packages/@romejs/js-compiler/transforms/lint/unusedVariables.ts`
- test: `packages/@romejs/js-compiler/transforms/lint/__rtests__/unusedVariables.ts`

I'd be happy to rename the test files to be suffixed with `.test.ts` but afaict there's no such convention here. I personally prefer that suffix but consistency among the project is more important.

Here's another file with such a structure:

- implementation: `packages/@romejs/path-match/parse.ts`
- test: `packages/@romejs/path-match/__rtests__/parse.ts`

**Comment by sebmck** [comment]
Thank you! Could you rebase and update the snapshots? #152 makes the format a lot nicer.

**Comment by yangshun** [comment]
Ok done! Please help to double check that I didn't miss out any tests when splitting the large test file up. I checked through once but it would be good to have a second pair of eyes.

**Comment by sebmck** [comment]
Great, thank you!

**Pull request merged**
