### PR TITLE
Add suggest package for improved error messages

### PR DESCRIPTION
**Pull request by mattsjones**
This WIP PR adds a "did you mean" type suggestion system to Rome through the `@romejs/suggest` package. The package can suggest a correct value from set that is similar to an incorrect user input value. 

image

I've always felt this is a massively unused tool in validation as it often saves users from having to look-up docs, or quickly fix typos that result in confusing error messages. 

Currently, I have only integrated it into the reading of rome config, but I think this package could be used in a variety of cases within the code (lint rules, type checking, etc). Effectively, anywhere that a value is part of a set of known values. 

As one of Rome's goals is to provide as much help and context to users when errors occur I thought this would be useful to the project. 

If we like the idea of this, could I have some feedback about how we'd like it integrated. 

- I wasn't sure whether it should be built into the diagnostics first class? Or just add when necessary.
- `@romejs/suggest` is a bit generic. Maybe `@romejs/did-you-mean` is better?

Note: I copied the source of sindresorhus's awesome [leven](https://github.com/sindresorhus/leven) package into rome and modified it slightly for TypeScript. The package is written for speed above all else which we may choose to tidy up in favour of more type-safety/readability.

### CODE REVIEW

**Comment by sebmck** [comment]
Nice! Huge fan of reusing `Consumer` and `usedNames` to do this so it's supported everywhere.

I don't actually think the suggest package is necessary as we have `@romejs/string-utils/findClosestStringMatch.ts` that we use in other places. In fact, we have `buildSuggestionAdvice` in `@romejs/diagnostics/helpers.ts` where you pass in a value and a list of possible items and it builds up the suggestion advice for you.

**Comment by mattsjones** [comment]
Haha course I missed that! 😅 Realising how much I rely on dependencies to understand a new codebase from scratch. Will be good to get some contributor docs for this stuff soon. 

Will refactor the module out and use the existing utils. 

Is `Consumer` purely for config handling? Or is it a lower level abstraction for something else?

**Comment by sebmck** [comment]
`Consumer` is for basically processing an unknown set of values. It's used for config loading, any JSON processing, CLI flag parsing etc.

**Comment by sebmck** [comment]
Love it! Thank you!

**Pull request merged**
