### PR TITLE
Update bash script snippet to make it work on unix devices

### PR DESCRIPTION
**Pull request by natealcedo**

### CODE REVIEW

**Comment by sebmck** [comment]
Change looks good to me. What do you mean by making it work on unix devices? I use Linux and all the shells I use allow relative paths to be executed this way. Happy to merge this anyway.

**Comment by natealcedo** [comment]
Oh terribly sorry. I meant unix based devices. i.e macos and linux. Cheers! :)

**Comment by sebmck** [comment]
I knew what you meant, I just don't know what shell `./scripts/dev-rome` would work but `scripts/dev-rome` wouldn't. Is this an error you actually ran into?

**Comment by natealcedo** [comment]
Oh you're right. It worked as you've mentioned. TIL. I mistakenly assumed it wouldn't work because I rely on tab completion  to run binaries in the directory I'm in. Do you want to leave it as such?

**Pull request merged**
