### PR TITLE
Tweak website landing page

### PR DESCRIPTION
**Pull request by yangshun**
Improve the landing page. Check out the site at - https://romejs.now.sh/ (I didn't mean to take that namespace, I'm more than willing to hand it over if the project maintainers want it).

Screen Shot 2020-03-01 at 11 04 17 PM

### CODE REVIEW

**Comment by zinyando** [comment]
This looks great, great work @yangshun!!!

**Comment by weblancaster** [comment]
Nice work @yangshun

**Comment by sebmck** [comment]
This is great, thank you so much!

**Comment by yangshun** [comment]
The next step would be to deploy it, possibly on Netlify. I saw that @Daniel15 created a Rome Netlify team. Would we be using that or should we use the [Facebook Open Source Netlify team](https://app.netlify.com/teams/facebook-open-source)?

**Comment by sebmck** [comment]
@Daniel15 already setup Netlify and the website autodeploys and is live now at https://romejs.dev/

**Comment by yangshun** [comment]
That's awesome! Thanks @Daniel15!

**Comment by Daniel15** [comment]
I did create the new Rome Netlify team before realizing that the FB open source one exists. I moved the site to that one :)

**Pull request merged**
