### PR TITLE
set license MIT in package.json

### PR DESCRIPTION
**Pull request by kandros**
set packages al MIT licensed as specified in the readme instead of private

### CODE REVIEW

**Comment by hsjoberg** [comment]
You might wanna add a `LICENSE` file as well.

**Comment by sebmck** [comment]
These packages are deliberately `private` as they are only for internal organization and there's no intention of ever publishing them to npm. The only package that will be published is `packages/rome`. Could you update this PR to just update the root `package.json` and `packages/rome/package.json` with the `license` field?

**Comment by kandros** [comment]
@sebmck is the LICENSE file supposed to be in `packages/rome/package.json` or will be copied from root at publish time?

**Comment by sebmck** [comment]
You can copy it there too. Could you add `"files": ["LICENSE"]` inside of `packages/rome/package.json` too? Right now when a release is built all files are omitted besides those that are referenced in the `main` and `bin` fields of `package.json`.

**Comment by kandros** [comment]
thank you for your patience 😅

**Comment by sebmck** [comment]
Thank you so much! I really appreciate it.

**Pull request merged**
