### PR TITLE
Adding tests for string-utils

### PR DESCRIPTION
**Pull request by Geenzo**
Adding some basic tests for the string-utils used in `/@romejs`

### CODE REVIEW

**Comment by sebmck** [comment]
This is awesome! Thank you so much! Looks like the files aren't formatted correctly though. Could you reformat them with prettier?

**Comment by sebmck** [comment]
I just pushed #59. If you rebase you should be able to run `./scripts/prettier-format` and the files will be formatted for you!

**Comment by Geenzo** [comment]
@sebmck formatted changes with prettier 😄

**Comment by sebmck** [comment]
Thank you so much @Geenzo!

**Pull request merged**
