### PR TITLE
extending testApi with decorator

### PR DESCRIPTION
**Pull request by tanhauhau**
I was thinking about https://github.com/facebookexperimental/rome/issues/94#issuecomment-593436846,

would it be useful that we can extending the testAPI to have custom assertions?

or prefer to have helper functions for testing like https://github.com/facebookexperimental/rome/pull/115?

### CODE REVIEW

**Comment by sebmck** [comment]
Seems like an unnecessary abstraction. Is there any downside to just having helper methods?

**Comment by tanhauhau** [comment]
You would have to pass in the `t: TestApi` into the helper function

**Comment by sebmck** [comment]
That seems a lot simpler than having the decorator though. It doesn't seem worth it.

**Comment by tanhauhau** [comment]
Got it!.

**Pull request closed without merging**
